spring:
  application:
    name: uploader-service

server:
  port: 9050
  servlet:
    context-path: /api/v1/uploads

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

cloudinary:
  api-key: ${API_KEY}
  cloud-name: ${CLOUD_NAME}
  api-secret: ${API_SECRET}